max_width = 120
indent_style = "Visual"
reorder_imports = true
match_block_trailing_comma = false
trailing_comma = "Vertical"
fn_single_line = true
struct_lit_single_line = true
fn_args_density = "Compressed"
